### ISSUE TITLE
Error installing sebaubuntu-libs 

### ISSUE THREAD

**Issue by sanjeevstunner** [SebaUbuntu/aospdtgen#12]
$ pip install sebaubuntu-libs

ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.9,<4.0; 1.0.1 Requires-Python >=3.9,<4.0; 1.0.2 Requires-Python >=3.9,<4.0; 1.0.3 Requires-Python >=3.9,<4.0; 1.0.4 Requires-Python >=3.9,<4.0; 1.0.5 Requires-Python >=3.9,<4.0; 1.0.6 Requires-Python >=3.9,<4.0
ERROR: Could not find a version that satisfies the requirement sebaubuntu-libs (from versions: none)
ERROR: No matching distribution found for sebaubuntu-libs

**Comment by sanjeevstunner** [comment]
$ python --version
Python 3.8.13

**Comment by sanjeevstunner** [comment]
$ pip install .

Processing /workspace/aospdtgen
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.9,<4.0; 1.0.1 Requires-Python >=3.9,<4.0; 1.0.2 Requires-Python >=3.9,<4.0; 1.0.3 Requires-Python >=3.9,<4.0; 1.0.4 Requires-Python >=3.9,<4.0; 1.0.5 Requires-Python >=3.9,<4.0; 1.0.6 Requires-Python >=3.9,<4.0
ERROR: Could not find a version that satisfies the requirement sebaubuntu-libs<2.0.0,>=1.0.6 (from aospdtgen) (from versions: none)
ERROR: No matching distribution found for sebaubuntu-libs<2.0.0,>=1.0.6

**Comment by SebaUbuntu** [comment]
You need Python 3.9
