### ISSUE TITLE
Issues with OnePlusN10 dump

### ISSUE THREAD

**Issue by kronflux** [SebaUbuntu/aospdtgen#13]
This device does not seem to contain a value you look for in build.prop
`AssertionError: Property ro.product.bootimage.model could not be found in build.prop`

I added this manually and it continues, however it would be nice if this was not necessary.
this is the dump:
[https://dumps.tadiphone.dev/dumps/oneplus/oneplusn10/](url)

After adding that, I do get a device tree generated, however I also get these warnings:

`[2022-05-12 20:56:32,780] [manifest.py:76 WARNING] import_file: Unknown HAL type native`
`[2022-05-12 20:56:33,972] [__init__.py:104 INFO] __init__: Cloning AIK...`
`[2022-05-12 20:56:37,883] [__init__.py:104 INFO] __init__: Cloning AIK...`

Hopefully this helps!

**Comment by SebaUbuntu** [comment]
I can make model prop optional
While the warning is fine

**Comment by SebaUbuntu** [comment]
Should be fixed with https://github.com/SebaUbuntu/aospdtgen/commit/14cb0d6ced506dc6460c3bcff2c259023f2232f9
