### ISSUE TITLE
Lack dash sign for some proprietary files

### ISSUE THREAD

**Issue by wbs306** [SebaUbuntu/aospdtgen#19]
Some proprietary files like apk, vintf, etc. file need the dash sign in proprietary-files.txt to build. But I don't know how to modify the source code to do this thing. Can we add this sign when doing `section.get_files()`?

**Comment by SebaUbuntu** [comment]
With this script I target LineageOS 19.1, and extract-utils automatically treats all of this files as build targets
What version are you building?

**Comment by wbs306** [comment]
I'm building EvolutionX Snow, maybe it will do the same thing.
