### ISSUE TITLE
Error  on building on5xelte device tree 

### ISSUE THREAD

**Issue by DiwasNpl** [SebaUbuntu/aospdtgen#22]
root@fv-az90-984:/home/diwas/on5xelte# python3 -m aospdtgen /home/diwas/on5xelte
Android device tree generator
Version 0.1.0
                                                                                        [INFO] Parsing all_files.txt                                                            [INFO] Figuring out partitions scheme                                                   Traceback (most recent call last):                                                        File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,                                            File "/usr/lib/python3.8/runpy.py", line 87, in _run_code                                 exec(code, run_globals)                                                               File "/usr/local/lib/python3.8/dist-packages/aospdtgen/__main__.py", line 11, in <module>                                                                                         main()                                                                                File "/usr/local/lib/python3.8/dist-packages/aospdtgen/main.py", line 31, in main         dump = DeviceTree(args.dump_path)                                                     File "/usr/local/lib/python3.8/dist-packages/aospdtgen/device_tree.py", line 43, in __init__                                                                                      self.partitions = Partitions(self.path)                                               File "/usr/local/lib/python3.8/dist-packages/aospdtgen/utils/partitions.py", line 37, in __init__
    assert PartitionModel.VENDOR in self.partitions
AssertionError

**Comment by SebaUbuntu** [comment]
Your device doesn't have a vendor partition, right?

**Comment by DiwasNpl** [comment]
Ya what to do ? This is the dump I used
https://dumps.tadiphone.dev/dumps/samsung/on5xelte/tree/on5xeltejv-user-8.0.0-R16NW-G570FXXS3CTF2-release-keys/

**Comment by DiwasNpl** [comment]
My device have vendor in path system/vendor

**Comment by SebaUbuntu** [comment]
https://dumps.tadiphone.dev/dumps/samsung/on5xelte/-/blob/on5xeltejv-user-8.0.0-R16NW-G570FXXS3CTF2-release-keys/system/build.prop#L176
